version: "3.9"
   
services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=namedb
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=dbpass
    
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./medusa_light:/medusa_light_project
      - ./data_static/web:/vol/web
    environment:
      - SECRET_KEY=django-insecure-q&j246(1x2-zymmkhv
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=namedb
      - DB_USER=userdb
      - DB_PASS=dbpass
    ports:
      - "8000:8000"
    depends_on:
      - db
